---
title: "Assessment 1.1"
author: "Oksana Kuchma 4661806"
date: "19/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **R Markdown editing**
## R Markdown is a file format for making dynamic documents with R. An *R Markdown* document is written in markdown **(an easy-to-write plain text format)**

```{r fastfood}
fastfood <-read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")
```
#** apply libarary
```{r}
library(tidyverse)
library(skimr)
library(janitor)
library(dplyr)
```

```{r}

fastfood10 <- fastfood %>% head(10) #displaying first 10 rows of fastfood.
```


```{r 2}
knitr::kable(fastfood10 [, 1:5]) #displaying first 10 rows and 5 variables
```

```{r 3}
fastfood10 %>% filter( calories>1000) #displaying calories more than 1000
```

```{r 4}
dont_eat_this <- fastfood10 %>% filter(total_fat>40 & total_carb>80) #displaying the observations with total fat > 40 and total_card>80 and assigned to variable dont_eat_this
```

```{r 5}

Mcdonalds <-  fastfood %>% filter(restaurant == "Mcdonalds") #displaying restaurant mcdonalds
```
